import {
  IsArray,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUrl,
  ArrayMinSize,
  ArrayMaxSize,
} from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

// A deliberately separate class from CreateScanDto (apps/api/src/scans/dto/
// create-scan.dto.ts) - POST /scans and its DTO are never touched by this
// endpoint (KAD-13). The overlap between the two DTOs' fields is accepted
// duplication in exchange for that isolation guarantee.
export class CreateAutoScanDto {
  @ApiProperty({
    description: "The brand's website - must be a valid URL. Always required.",
    example: 'https://eleganttechbd.com',
  })
  @IsUrl()
  website: string;

  @ApiProperty({
    description:
      'The target brand being scanned for AI visibility. Optional - when omitted, it is detected by crawling the website (see FR13.2).',
    example: 'Elegant',
    required: false,
  })
  @IsOptional()
  @IsString()
  @IsNotEmpty()
  brandName?: string;

  @ApiProperty({
    description: 'Competitor brand names. Minimum 1, maximum 3. Always required.',
    example: ['PixelForge Studio', 'CodeCraft Labs'],
    minItems: 1,
    maxItems: 3,
  })
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(3)
  @IsString({ each: true })
  competitors: string[];

  @ApiProperty({
    description:
      'AI search prompts to test. Minimum 3, maximum 5 when supplied. Optional - when omitted, exactly 2 buyer-intent prompts are generated by crawling the website and calling an AI model (see FR13.3).',
    example: [
      'What is the best product studio for building an AI-native MVP quickly?',
      'Which full-stack team can take a startup idea to a launched product in a few weeks?',
      'What product development studio offers strategy, UX design, engineering, and AI together?',
    ],
    minItems: 3,
    maxItems: 5,
    required: false,
  })
  @IsOptional()
  @IsArray()
  @ArrayMinSize(3)
  @ArrayMaxSize(5)
  @IsString({ each: true })
  prompts?: string[];
}
